---
resources:
- name: concourse-arm64
  type: git
  icon: github
  source:
    uri: https://github.com/robinhuiser/concourse-arm64

jobs:
- name: test-job
  public: true
  plan:
  - get: concourse-arm64
    trigger: true
  - task: build-task
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: rdclda/concourse-oci-build-task
          tag: latest
      inputs:
      - name: concourse-arm64
      outputs:
      - name: image
      params:
        CONTEXT: concourse-arm64/external-tasks/oci-build/example
      run:
        path: build
      caches:
      - path: cache
